### ISSUE TITLE
how to load gems on gemset as local gems

### ISSUE THREAD

**Issue by ylbeethoven** [inscapist/ruby-nix#31]
Hi,

I generated _flake.nix_ with `nix flake init -t github:inscapist/ruby-nix/main`. 

Then I use `bundix` to generate the _gemset.nix_. 

Next I use `nix developer -c $SHELL` to build the dependencies and it gives me a shell,  this also works.

Inside the shell, I notice that the gems specify on _gemset.nix_ are not listed as local gems `gem list` and I am guessing this is the reason my project throws below error when I tried to build. 

```bash
21:13:37 vite.1   | /nix/store/jsmycnp95j8nfj3yb1a471hc4ini939w-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/definition.rb:540:in `materialize': Could not find foreman-0.87.2 in locally installed gems (Bundler::GemNotFound)
```

On _gemset.nix_ I have
```yaml
  foreman = {
    groups = ["development"];
    platforms = [];
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "0szgxvnzwkzrfbq5dkwa98mig78aqglfy6irdsvq1gq045pbq9r7";
      target = "ruby";
      type = "gem";
    };
    targets = [];
    version = "0.87.2";
  };
```

> In fact, if I use `bundle info GEM` to check the gem specified on _gemset.nix_, I am getting warning message all gems specified on this file could not be found in locally installed gems.

Does anyone know how to load gems on gemset to local gems?

**Comment by inscapist** [comment]
Sorry for the slow response. Is your local gem specified in your top level Gemfile?

For example
```
...
gem 'local_gem', path: 'lib/local_gem'
```

**Comment by ylbeethoven** [comment]
> Sorry for the slow response. Is your local gem specified in your top level Gemfile?
> 
> For example
> 
> ```
> ...
> gem 'local_gem', path: 'lib/local_gem'
> ```

Thanks for the reply.

This is a jekyll project, I have below on the `Gemfile`

```text
gem 'jekyll', '4.2.2'
gem 'jekyll-include-cache'
gem 'jekyll-redirect-from'
gem 'jekyll-generator-single-source'
gem 'kramdown-parser-gfm'
gem 'liquid-c'
gem 'rouge', '3.30.0'
gem 'activesupport'
gem 'nokogiri'
gem 'jekyll-xxx-plugins', path: './app/_src/.repos/xxx/jekyll-xxx-plugins'
gem 'jekyll-vite'
```

**Comment by ylbeethoven** [comment]
I am closing this issue because it's not worthwhile to persuade my team to use Nix to set up their dev environment.

**Comment by LoganBarnett** [comment]
I've observed a similar problem I think, and I would suggest reopening this.

What seems to be happening is that `gemset.nix` doesn't get re-evaluated when it changes.  I'll try to get a public reproduction going to demonstrate it.

Basically my steps are:
1. Add a gem `foo` declaration in my `bar.gemspec` file.
2. Run `bundle lock && bundix --lock`.
3. Just to be sure, run `direnv allow`.  This is instant and doesn't seem to actually do anything in terms of picking up the new gems.
4. Run `gem list | grep foo` and observe there is no gem.
5. Alternatively if one is attempting to upgrade a gem, you may find the gem but it will be the old version.

During the course of debugging this, something happens where Nix forces a re-evaluation of the right thing and the gems get picked up, and I can move on.  I've written down steps in the past I thought I had taken, but none of them work when the issue comes back up later.

I realize I'm using `direnv` here and thus it might be involved.  I haven't decoupled it from my setup of the issue yet.

I do have a `watch_file gemset.nix` in `.envrc`.  This has been blessed with `direnv allow` but I can go into the file and even make manual changes (like removing the hash on a gem) and no changes get picked up automatically nor on a `direnv allow`.

**Comment by LoganBarnett** [comment]
Alright, I have a local reproduction here: https://github.com/LoganBarnett/ruby-nix-gemset-non-update

The README covers reproduction steps.  There's probably more to simplify, but this is significantly simplified over my `$WORK` setup ;)  Happy to accommodate on that, but I wanted to get something out there.

I want to acknowledge that I'm not doing the `bundix --magic` step.  I can't get this to work because I'm running a pure Flake setup on my machines.  There are no Nix channels configured, so I can't simply pluck `bundix` from there.  That said, I'm providing `bundix` via my `devShell`.

This is the error with `bundix --magic`:

```
$ bundix --magic
warning: Nix search path entry '/Users/logan/.nix-defexpr/channels' does not exist, ignoring
error:
       … <borked>

         at «none»:0: (source not available)

       … while calling the 'import' builtin

         at «string»:1:18:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (ruby) (bundler.override { ruby = ruby; }) ]; } ""
             |                  ^

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «none»:0: (source not available)
/nix/store/46yrpr6iqfzkas8b7mixjpi2qsdb4rss-bundix-2.5.2/lib/ruby/gems/3.3.0/gems/bundix-2.5.0/lib/bundix/commandline.rb:103:in `handle_magic': unhandled exception
	from /nix/store/46yrpr6iqfzkas8b7mixjpi2qsdb4rss-bundix-2.5.2/lib/ruby/gems/3.3.0/gems/bundix-2.5.0/lib/bundix/commandline.rb:33:in `run'
	from /nix/store/46yrpr6iqfzkas8b7mixjpi2qsdb4rss-bundix-2.5.2/lib/ruby/gems/3.3.0/gems/bundix-2.5.0/lib/bundix/commandline.rb:22:in `run'
	from /nix/store/46yrpr6iqfzkas8b7mixjpi2qsdb4rss-bundix-2.5.2/lib/ruby/gems/3.3.0/gems/bundix-2.5.0/bin/bundix:5:in `<top (required)>'
	from /nix/store/46yrpr6iqfzkas8b7mixjpi2qsdb4rss-bundix-2.5.2/bin/.bundix-wrapped:18:in `load'
	from /nix/store/46yrpr6iqfzkas8b7mixjpi2qsdb4rss-bundix-2.5.2/bin/.bundix-wrapped:18:in `<main>'
```

I've also had trouble where I wanted a specific Ruby version used and `bundix` couldn't find it, presumably for the same reasons (`nix-shell` can't see the Flake environment, is my guess).

I've also tried doing the exact same `bundle pack ...` invocation that `bundix --magic` wouldn've done (I'm already doing the `bundle lock` step manually), and it's resulted in no change in behavior.

Apologies if this distracts from the original issue - I felt it relevant to include because it's part of the invocation steps for `ruby-nix` and I've been skipping it - perhaps somehow causing this very issue.

**Comment by inscapist** [comment]
Skimming through, it looks like there are several issues here, and I don't think they are related to the original issue, which has to do with the addressability of local gems.

But let me check out your local repro in my spare time this weekend. As for the issue of direnv not picking up your gemset changes, chances are it's unrelated to this project as well. 

It rarely happens for me, but when it does, I would just do `rm -rf .direnv`. There was [a conversation](https://github.com/nix-community/nix-direnv/issues/51) about this as well

**Comment by LoganBarnett** [comment]
I meant to follow up on this.  It looks like they made a `nix_flake_watch_file` but then moved it back into `watch_file`.  Running `rm -rf .direnv && direnv allow` seems to do the trick though.  Thanks!!
